### ISSUE TITLE
Does CNA support multiple unordered variables?

### ISSUE THREAD

**Issue by altairwei** [immunogenomics/cna#12]
Hi,

I would like to know if CNA supports multiple unordered variables. As we known, the Pearson and Spearman’s correlation can handle binary or continuous variables or ordered categorical values, but they cannot handle multiple unordered categories. In the article (Reshef, Y. A. et al., _Nature Biotechnology_, 2021), all tree examples are based on binary variables.

Best,

**Comment by yakirr** [comment]
Hi there -- as currently implemented, CNA would require binary variables.
In principle it could be extended to unordered categories, but we have not
done this. One workaround that at least partially addresses your need
though would be encode your unordered categorical variable as a series of
binary variables. For example, if you have a variable "color" that can be
"red", "green", or "blue". You could create three binary variables
"is_red", "is_green", and "is_blue". This is not a perfect solution because
you can't jointly test all of the variables for association, but perhaps it
will give you an initial way of assessing whether there's signal in the
data.

**Comment by altairwei** [comment]
@yakirr Thank you for your advice! This is indeed a workaround. Any suggestions on continuous variables or ordered categorical values?

**Comment by yakirr** [comment]
Continuous variables should work fine -- just plug them in. Ordered
categorical variables are a bit trickier -- you can always just code the
categories as {1,2,3...} and plug them in since they're ordered, but be
aware that they will be fit via a linear model so the assumption is that
whatever enrichment differentiates category 1 from category 2 will also
equally differentiate category 2 from category 3.

**Comment by altairwei** [comment]
@yakirr Got it! Thank you again!
