### ISSUE TITLE
Experimental set up

### ISSUE THREAD

**Issue by olabylinska** [immunogenomics/cna#18]
Hi, I was trying to implement CNA on my scRNA-Seq data but I am not confident in the results I’m getting and I’m wondering whether my set up is correct. I have 4 comparison groups and multiple cell types I would like to look at for a total of 32 samples. 

1. My current _d.samplem_ is a table with each comparison group as a column) and when I’m running _cna.tl.association_, I specify _d.samplem.comparisongroup_ as an argument. Is that a correct set up?

2. Every time I’m running _cna.tl.association_ I’m getting a different global association p-value. Is that expected?
 
3. For most of the groups I’m getting “no neighborhoods were significant at FDR < 0.05” (despite some pvalues being <0.05), while I would expect to see some differences between the groups. Can it be affected by an incorrected set up or there are just no major differences that CNA would pick up on?

4. My input file is an _anndata_ object (after batch correction, with umap) – do I need to rerun _sc.pp.neighbors_ and _umap_ after creating _MultiAnnData_ object?

Is CNA adequate for my experimental set up or is it more recommended for case/control analysis?
Thank you for help!

**Comment by rumker** [comment]
Hi there, we're happy to help with these questions! I've added responses below:

**1. My current d.samplem is a table with each comparison group as a column) and when I’m running cna.tl.association, I specify d.samplem.comparisongroup as an argument. Is that a correct set up?**
In the call to `cna.tl.association`, you should offer the values per sample for your variable of interest as the vector assigned to parameter `y`. In your case, it sounds like, for a given one-versus-rest comparison among your groups, `y` should take values of 1 for all samples in your selected group and values of 0 for the remaining samples.

**Every time I’m running cna.tl.association I’m getting a different global association p-value. Is that expected?**
CNA uses permutations to construct a null distribution, so unless you set a consistent seed, we would expect some variation. In order to generate results that replicate consistently, add a line like: `np.random.seed(0)`

**For most of the groups I’m getting “no neighborhoods were significant at FDR < 0.05” (despite some pvalues being <0.05), while I would expect to see some differences between the groups. Can it be affected by an incorrected set up or there are just no major differences that CNA would pick up on?**
Our global association test (result stored in `res.p`) and local association test (results stored in `res.fdrs`, `res.fdr_5p_t`, and `res.fdr_10p_t`) ask slightly different questions. The global association test evaluates whether there is a significant relationship between your attribute of interest and the global distribution of cell density for each sample across your neighborhoods. The local association test evaluates, per neighborhood, whether the strength of correlation between sample fractional abundance _in that one neighborhood_ and your attribute of interest is larger than we would expect by chance alone. In your case, it sounds like the global association tests indicate there is a significant and systematic change in cellular composition associated with your sample groupings, but the dataset might not offer enough power to localize the signal to specific neighborhoods.

**My input file is an anndata object (after batch correction, with umap) – do I need to rerun sc.pp.neighbors and umap after creating MultiAnnData object?**
MultiAnnData will inherit the components in your AnnData object, including nearest neighbor graph and umap results. You can double check this by printing out the object components after making your MultiAnnData object.

**Is CNA adequate for my experimental set up or is it more recommended for case/control analysis?**
The CNA package readily supports the approach you have taken so far (i.e., one-versus-rest association tests for each of your sample subgroups). If I am understanding correctly, your samples are divided into four subgroups of interest and you would like to test whether cellular composition varies significantly across those subgroups. To turn this question into a single test you could use an ANOVA approach (you can access sample loadings on NAM-PCs for your own modeling as `d.uns['NAM_sampleXpc'].iloc[:,:k]` for the top `k` NAM-PCs). In such a model, the null hypothesis would be that all of your subgroups are the same and the alternative hypothesis would be that _at least one_ subgroup differs from the rest. However, given a significant result from this unified test you would likely next be interested in pairwise or one-versus-rest comparisons in order to specifically define the contrasts among your groups, so given that you already have significant global associations by CNA for your one-versus-rest tests, I think it is not unreasonable to stick with your current approach.

I hope this helps and best wishes for your work!
