### ISSUE TITLE
Result interpretation

### ISSUE THREAD

**Issue by olabylinska** [immunogenomics/cna#20]
I have a question regarding interpretation of my results - very often I'm getting a plot like this, with both colors overlapping on the same cluster. What would be an appropriate way of interpreting such results? I'm not really seeing a clear separation that was presented in the tutorial.

![cna_corr](https://github.com/user-attachments/assets/1c2a19c3-038d-4811-8099-a8f2fb9db3af)

**Comment by rumker** [comment]
Hi @olabylinska, thanks for reaching out! A result like the one you've shown here can occur when the module(s) of genes that characterize your expanded or depleted neighborhoods are not the same as the genes most influencing the cells' location along the UMAP axes. We highlight an example like this in the CNA paper: neighborhoods with altered abundance in association with a male/female sex attribute were visually distributed across the UMAP plot because the gene modules characterizing those neighborhoods (sex chromosome genes) were not the gene modules most driving the cells' positions along the UMAP axes (T cell subset marker genes). To explore what gene module(s) characterize your expanded and depleted cell groups, there are many strategies you could consider. As a starting point, you could look at the genes most correlated in expression with 1) cell membership in the depleted (or expanded) group, or 2) ncorrs values across all cells. In the sex example from our paper, a similar kind of approach revealed the sex chromosome genes as those whose expression was altered in neighborhoods associated with male/female sex.
